package com.marceloituccayasi.ocv.operationalclose.domain;

import java.util.UUID;

/**
 * Identifier of an Operational Event state transition.
 *
 * @param value UUID generated by the application
 */
public record EventStateTransitionId(UUID value) {

    public EventStateTransitionId {
        if (value == null) {
            throw new IllegalArgumentException(
                    "event state transition id must not be null");
        }
    }

    @Override
    public String toString() {
        return value.toString();
    }

}