package com.marceloituccayasi.ocv.operationalclose.domain;

import java.util.UUID;

/**
 * Identifier of an Operational Event.
 *
 * @param value UUID generated by the application
 */
public record OperationalEventId(UUID value) {

    public OperationalEventId {
        if (value == null) {
            throw new IllegalArgumentException(
                    "operational event id must not be null");
        }
    }

    @Override
    public String toString() {
        return value.toString();
    }

}